mysite/blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'
urlpatterns = [
    # post views
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,
        name='post_detail'),
    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_no>.+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^postlikes/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_likes,name='post_likes'),
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog.views import *



urlpatterns = [
    url(r'',include('blog.urls', namespace='blog')),
    url(r'^admin/', admin.site.urls),
    # url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^blog/', blog.views.post_detail),
]


#import debug_toolbar
#urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')

class Tag(models.Model):
    no=models.IntegerField(primary_key=True)
    name=models.CharField(max_length=80)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering=('created',)

    def __str__(self):
        return self.name

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, related_name='blog_posts',on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    objects = models.Manager() # The default manager.
    published = PublishedManager() # The Dahl-specific manager.

    tags=models.ManyToManyField('Tag')

    likenum=models.IntegerField(default=0)

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])
    def get_absolute_like_url(self):
        return reverse('blog:post_likes', args=[self.publish.year,
                                                 self.publish.strftime('%m'),
                                                 self.publish.strftime('%d'),
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments',on_delete=models.CASCADE)
    name = models.CharField(max_length=80)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

mysite/blog/forms.py
from django import forms
from .models import Comment
from django.forms import widgets as Fwidgets

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'body')
        labels = {
            'name': '姓名',
            'body': '评论',
        }
        help_texts = {
            'name': '用户名',
            'body': '文明社会,理性评论',
        }
        widgets = {
            'name': Fwidgets.TextInput(attrs={'class': 'form-control','placeholder':'请输入名称'}),
            'body': Fwidgets.Textarea(attrs={'class': 'form-control','rows':'3','placeholder':'文明社会,理性评论'}),
        }
        error_messages = {
            'name':{
                'required': '姓名不能为空'
            },
            'body':{
                'required': '评论不能为空'
            }
        }

    #def __init__(self,*args,**kwargs):
    #	super(CommentForm,self).__init__(*args,**kwargs)
    #	for field_name in self.base_fields:
    #		field=self.base_fields[field_name]
    #		field.widget.attrs.update({'class':"form-control"})

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count
from django.http import HttpResponse
import json

#from taggit.models import Tag

from .models import Post, Comment,Tag
from .forms import EmailPostForm, CommentForm

import logging

logging.basicConfig(filename='logger.log', level=logging.INFO)

def post_list(request, tag_no=None):
    object_list = Post.published.all()
    tag = None

    if tag_no:
        tag = get_object_or_404(Tag, no=tag_no)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 5) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list1.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list1.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
         # A comment was posted
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, 'blog/post/detail1.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form':comment_form})

  
def post_likes(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    if request.method == 'POST':
        post.likenum +=1
        post.save()

        ret={}
        ret['data'] = post.likenum
        ret['status'] = 0

        return HttpResponse(json.dumps(ret), content_type="application/json")
    else:
        comments = post.comments.filter(active=True)
        comment_form = CommentForm() 

    return render(request, 'blog/post/detail1.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form':comment_form}) 


     




def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})

mysite/blog/templates/blog/base.html
{% load blog_tags  %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    <link href="{% static "css/bootstrap-3.3.7-dist/css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/jquery-3.2.1/jquery-3.2.1.min.js" %}" rel="stylesheet">
    <link href="{% static "css/bootstrap-3.3.7-dist/js/bootstrap.min.js" %}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-inverse">
     <div class="container-fluid">
      <div class="navbar-header">
       <a class="navbar-brand" href="#"> </a>
       <p class="navbar-text">HPY's Blog</p>
      </div>
     </div>
    </nav>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>My blog</h2>
        <p>This is my blog. I've written {% total_posts %} post so far</p>
        <h3>最新文章</h3>
        {% show_last_posts 3 %}
        <h3>分类</h3>
         {% get_tags_count as tags_count %}
        <ul>
         {% for tag in tags_count %}
        <li>
          <a href="{% url "blog:post_list_by_tag" tag.no %}">{{ tag.name}} ({{ tag.total_post }})</a>
        </li>
        {% endfor %}
        </ul>
    </div>
</body>
</html>

mysite/blog/templates/blog/base1.html
{% load blog_tags  %}
{% load custom_markdown  %}
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>HPY's Blog</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="{% static "css/bootstrap-3.3.7-dist/css/bootstrap.min.css" %}" rel="stylesheet">
<script src="{% static "css/jquery-3.2.1/jquery-3.2.1.min.js" %}" type="text/javascript"></script>
<script src="{% static "css/bootstrap-3.3.7-dist/js/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "css/highlight/highlight.pack.js" %}" type="text/javascript"></script>
<link href="{% static "css/highlight/styles/monokai.css" %}" rel="stylesheet" >
<link href="{% static "css/blog1.css" %}" rel="stylesheet">
<script>hljs.initHighlightingOnLoad();</script>
<script type="text/javascript">
function likes_topic(){
       $.ajax({
            beforeSend:function(xhr, settings) {
                    function getCookie(name) {
                            var cookieValue = null;
                            if (document.cookie && document.cookie != '') {
                                var cookies = document.cookie.split(';');
                                for (var i = 0; i < cookies.length; i++) {
                                    var cookie = jQuery.trim(cookies[i]);
                                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                        break;
                                    }
                                }
                            }
                            return cookieValue;
                        }
                        if (settings.url == "{{ post.get_absolute_like_url }}")
                            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                    },
            type:'POST',
            url:'{{ post.get_absolute_like_url }}',
            dataType:'json',
            success:function(data, status){
                $("#likenum").text(data['data']);
                }
    });
}
</script>
<script type="text/javascript">
$(function(){ 
$('#AClikenum > a').bind("click",function(){
   var t=$(this);
   $.ajax({
            type:'POST',
            url:$(this).attr("value"),
            beforeSend:function(xhr, settings) {
                    function getCookie(name) {
                            var cookieValue = null;
                            if (document.cookie && document.cookie != '') {
                                var cookies = document.cookie.split(';');
                                for (var i = 0; i < cookies.length; i++) {
                                    var cookie = jQuery.trim(cookies[i]);
                                    if (cookie.substring(0, name.length + 1) == (name + '=')) {
                                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                        break;
                                    }
                                }
                            }
                            return cookieValue;
                        }
                        xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                    },
            async: false,
            dataType:'json',
            success:function(data, status){
                t.next('span').text(data['data']);
                }
    });
});
})
</script>
</head>
<body>

<nav class="nav navbar-inverse navbar-fixed-top" role="navgation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="#" class="navbar-brand">
            </a>
            <p class="navbar-text" style="padding-left:90px;" id="ABtitle">
            <a href="{% url "blog:post_list" %}">
            HPY's Blog
            </a></p>
        </div>
    </div>
</nav>

<div class="container-fluid" style="margin-top: 70px;margin-bottom: 70px;">
        <div class="col-md-7 col-md-offset-1">
            {% block content %}
            {% endblock %}
        </div>
        <!-- 侧边栏 -->
        <div class="col-md-3 ">
            <div class="panel panel-default">
                <div class="panel-body" style="
                background:url({% static "img/Ddt.jpg"%}); background-size:100% 100%; background-repeat:no-repeat; font-family: "Source Code Pro" ">
                    <div class="user" >
                    <img  class="yj" src="{% static "img/V.jpg"%}" width="50px" height="50px">
                    <span style="display:inline;font-style:italic"> 每天进步一点点</span>
                    </div>
                    <div>
                    <ul  class="list-group" style="margin-top: 10px;  list-style-type:none">
                    <li lass="list-group-item" style="border: 0;" ><i class="glyphicon glyphicon-map-marker"></i>&nbsp;&nbsp;<strong style="font-style:italic">中国 杭州</strong></li>
                    <li lass="list-group-item" style="border: 0;"><i class="glyphicon glyphicon-picture"></i>&nbsp;&nbsp;<strong style="font-style:italic">1990-11-01</strong></li>
                    <!--li lass="list-group-item" style="border: 0;"><i class="glyphicon glyphicon-envelope"></i>&nbsp;&nbsp;<strong style="font-style:italic">hpymn123@163.com</strong></li-->
                    <li lass="list-group-item" style="border: 0;"><img src="{% static "img/github.png"%}" width="16px" height="16px">&nbsp;&nbsp;<strong style="font-style:italic">hpymn123@163.com</strong></li>
                    </ul>
                    </div>
                </div>
            </div>

            <!-- 近期文章 -->
            <div class="panel panel-success">
                <div class="panel-heading">
                    近期文章
                </div>
                {% Show_last_posts as show_posts %}
                <ul class="list-group">
                {% for post in show_posts %}
                  <li  class="list-group-item" style="border: 0;">
                       <span></span>
                       <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                  </li>
                {% endfor %}
                </ul>
            </div>

             <!-- 分组 -->
            <div class="panel panel-warning">
                <div class="panel-heading">
                    分类
                </div>
                {% get_tags_count as tags_count %}
                <div class="list-group">
                {% for tag in tags_count %}
                    <a href="{% url "blog:post_list_by_tag" tag.no %}" class="list-group-item">
                       {% if forloop.counter|get_mod:"5" == 1 %}
                       <span class="label label-primary">{{ tag.name}}</span>
                       {% elif forloop.counter|get_mod:'5' == 2 %}
                       <span class="label label-success">{{ tag.name}}</span>
                       {% elif forloop.counter|get_mod:'5' == 3 %}
                       <span class="label label-info">{{ tag.name}}</span>
                       {% elif forloop.counter|get_mod:'5' == 4 %}
                       <span class="label label-warning">{{ tag.name}}</span>
                       {% elif forloop.counter|get_mod:'5' == 0 %}
                       <span class="label label-danger">{{ tag.name}}</span>
                       {%  endif %}
                       <span class="badge">{{ tag.total_post }}</span>
                    </a>
                {% endfor %}
                </div>
            </div>

            <!-- 最新评论 -->
            <div class="panel panel-info">
                <div class="panel-heading">
                    最新评论
                </div>
                {% Show_last_comments as show_comments %}
                <div class="list-group">
                {% for comment in show_comments %}
                    <!--li class="list-group-item " style="border: 0;">
                       <span><strong>{{comment.name}}</strong>:<small>{{ comment.body |truncatewords:30|linebreaks}}</small></span>
                       <p class="disabled"><small>{{comment.created|date:"Y-m-d H:i:s"}}</small></p>
                    </li-->
                    <div class="list-group-item comment" style="padding-left: 10px;">
                    <p class="info" id="Alist">
                    <a href="{{ comment.post.get_absolute_url }}">{{ forloop.counter }}.{{ comment.post.title }}</a>
                    </p>
                    <P>
                    {{ comment.body|linebreaks }}
                    </P>
                    <P style="text-align:right">
                     --<strong>{{comment.name}}</strong>
                    </P>
                    </div>
                    <!--hr style="height:1px;border:none;border-top:1px solid #ddd;width:90%;"/-->
                {% endfor %}
                </div>
            </div>


           

        </div>
</div>

<div id="footer" class="container">
<nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="navbar-inner navbar-content-center">
        <p class="text-muted credit">
        </p>
    </div>

</nav>
</body>
</html>